name: example
description: An example of how the CaTeX package can be used in a Flutter app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  catex:
    path: ../

flutter:
  uses-material-design: true
